apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: root-dev-password
  mysql-password: ecommerce-dev-password
  mysql-database: ecommerce
  mysql-username: ecommerce