apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: mxmobilz
  source:
    repoURL: 'https://github.com/Hamzasarfrax/production-grade-cloud-native-e-commerce-platform'
    targetRevision: main
    path: gitops/base/backend
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: image.repository
        value: hamzasarfraz862/backend-app
      - name: image.tag
        value: "1.0.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: cloud-native-ecomerce-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true