apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- mysql/
- backend/
- frontend/
- ingress/
- network-policies/

labels:
  - pairs:
      app.kubernetes.io/part-of: mxmobilz
      app.kubernetes.io/managed-by: argocd