apiVersion: v2
name: backend-helm
description: Helm chart for Mxmobilz Laravel Backend (PHP-FPM + Nginx)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - laravel
  - php
  - nginx
  - ecommerce
  - mxmobilz
maintainers:
  - name: Hamza Sarfraz
    email: hamzasarfraz862@example.com
sources:
  - https://github.com/Hamzasarfrax/production-grade-cloud-native-e-commerce-platform