apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cloud-native-ecomerce-app

data:
  replicas-min: "3"
  replicas-max: "5"
  cpu-utilization: "70"
  memory-utilization: "70"