apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-app
    namespace: cloud-native-ecomerce-app  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
  spec:
     resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
      containers:
      - name: backend-app
        image: hamzasarfraz862/backend-app:1.0.0
        ports:
        - containerPort: 8000
