apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: cloud-native-ecomerce-dev

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend
    spec:
      replicas: 1
  target:
    kind: Deployment
    labelSelector: app=backend
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
    spec:
      replicas: 1
  target:
    kind: Deployment
    labelSelector: app=frontend
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: mysql
    spec:
      replicas: 1
  target:
    kind: StatefulSet
    labelSelector: app=mysql

configMapGenerator:
- name: env-config
  behavior: create
  literals:
  - ENVIRONMENT=development
  - LOG_LEVEL=debug

labels:
  - pairs:
      environment: dev