apiVersion: v1
kind: Secret
metadata:
  name: mysql-app-secret
  namespace: cloud-native-ecomerce-app
type: Opaque
stringData:
  mysql-root-password: root-dev-password
  mysql-password: ecommerce-dev-password
  mysql-database: ecommerce
  mysql-username: ecommerce