apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  namespace: cloud-native-ecomerce-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mysql-app-secret
    creationPolicy: Owner
  data:
  - secretKey: mysql-root-password
    remoteRef:
      key: mxmobilz/mysql
      property: root_password
  - secretKey: mysql-password
    remoteRef:
      key: mxmobilz/mysql
      property: password
  - secretKey: mysql-database
    remoteRef:
      key: mxmobilz/mysql
      property: database
  - secretKey: mysql-username
    remoteRef:
      key: mxmobilz/mysql
      property: username
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: laravel-app-key
  namespace: cloud-native-ecomerce-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: laravel-app-key
    creationPolicy: Owner
  data:
  - secretKey: APP_KEY
    remoteRef:
      key: mxmobilz/laravel
      property: app_key
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets-system