name: Docker Build, Scan & Push

on:
  push:
    branches:
      - dev
    tags:
      - "backend-v*.*.*"
      - "frontend-v*.*.*"

env:
  BACKEND_IMAGE: hamzasarfraz862/backend-app
  FRONTEND_IMAGE: hamzasarfraz862/front-end-app

jobs:
  docker:
    name: Build, Scan & Push Images
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # Checkout
      # -----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------------
      # Determine Component & Version
      # -----------------------------
      - name: Determine Image Tag
        id: version
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/backend-v* ]]; then
            COMPONENT="backend"
            VERSION="${GITHUB_REF#refs/tags/backend-v}"

          elif [[ "${GITHUB_REF}" == refs/tags/frontend-v* ]]; then
            COMPONENT="frontend"
            VERSION="${GITHUB_REF#refs/tags/frontend-v}"

          else
            COMPONENT="all"
            VERSION="${GITHUB_SHA}"
          fi

          echo "component=${COMPONENT}" >> "$GITHUB_OUTPUT"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

          echo "Component: ${COMPONENT}"
          echo "Docker version: ${VERSION}"

      # -----------------------------
      # Docker Buildx
      # -----------------------------
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # =========================================================
      # BACKEND
      # =========================================================

      - name: Build Backend Image
        if: steps.version.outputs.component == 'backend' || steps.version.outputs.component == 'all'
        run: |
          docker build \
            -t $BACKEND_IMAGE:${{ steps.version.outputs.version }} \
            ./backend

   
      # =========================================================
      # FRONTEND
      # =========================================================

      - name: Build Frontend Image
        if: steps.version.outputs.component == 'frontend' || steps.version.outputs.component == 'all'
        run: |
          docker build \
            -t $FRONTEND_IMAGE:${{ steps.version.outputs.version }} \
            ./frontend

      - name: Scan Frontend Image
        if: steps.version.outputs.component == 'frontend' || steps.version.outputs.component == 'all'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.FRONTEND_IMAGE }}:${{ steps.version.outputs.version }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      # =========================================================
      # DOCKER HUB LOGIN
      # =========================================================

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # =========================================================
      # PUSH BACKEND
      # =========================================================

      - name: Push Backend Image
        if: steps.version.outputs.component == 'backend' || steps.version.outputs.component == 'all'
        run: |
          docker push \
            $BACKEND_IMAGE:${{ steps.version.outputs.version }}

      # =========================================================
      # PUSH FRONTEND
      # =========================================================

      - name: Push Frontend Image
        if: steps.version.outputs.component == 'frontend' || steps.version.outputs.component == 'all'
        run: |
          docker push \
            $FRONTEND_IMAGE:${{ steps.version.outputs.version }}

      # =========================================================
      # LATEST TAG
      # =========================================================

      - name: Tag Backend as Latest
        if: steps.version.outputs.component == 'backend'
        run: |
          docker tag \
            $BACKEND_IMAGE:${{ steps.version.outputs.version }} \
            $BACKEND_IMAGE:latest

      - name: Tag Frontend as Latest
        if: steps.version.outputs.component == 'frontend'
        run: |
          docker tag \
            $FRONTEND_IMAGE:${{ steps.version.outputs.version }} \
            $FRONTEND_IMAGE:latest

      - name: Push Backend Latest
        if: steps.version.outputs.component == 'backend'
        run: |
          docker push $BACKEND_IMAGE:latest

      - name: Push Frontend Latest
        if: steps.version.outputs.component == 'frontend'
        run: |
          docker push $FRONTEND_IMAGE:latest
